# Generated by Django 5.0.7 on 2024-07-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_scrap"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="slug", max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
